CREATE TABLE products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  sku text UNIQUE NOT NULL,
  description text NOT NULL DEFAULT '',
  price_cents integer NOT NULL CHECK (price_cents >= 0),
  stock integer NOT NULL DEFAULT 0 CHECK (stock >= 0),
  reorder_threshold integer NOT NULL DEFAULT 5 CHECK (reorder_threshold >= 0),
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name text NOT NULL,
  customer_email text NOT NULL,
  status text NOT NULL DEFAULT 'new' CHECK (
    status IN ('new', 'packed', 'shipped', 'ready_for_pickup', 'completed', 'cancelled')
  ),
  fulfillment_type text NOT NULL CHECK (fulfillment_type IN ('pickup', 'shipping')),
  payment_status text NOT NULL CHECK (payment_status IN ('paid', 'unpaid', 'invoice')),
  total_cents integer NOT NULL DEFAULT 0 CHECK (total_cents >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE order_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id integer NOT NULL REFERENCES products(id),
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price_cents integer NOT NULL CHECK (unit_price_cents >= 0)
);

CREATE INDEX orders_created_at_idx ON orders (created_at DESC);
CREATE INDEX orders_status_idx ON orders (status);
CREATE INDEX order_items_order_id_idx ON order_items (order_id);

INSERT INTO products (name, sku, description, price_cents, stock, reorder_threshold) VALUES
  ('House Coffee Beans', 'COFFEE-001', 'Single-origin light roast, 250g bag', 1800, 45, 8),
  ('Ceramic Camp Mug', 'MUG-001', 'Hand-thrown 12oz ceramic, dishwasher safe', 2400, 20, 8),
  ('Canvas Tote Bag', 'TOTE-001', 'Heavyweight natural cotton canvas', 1600, 30, 8),
  ('Field Notebook', 'NB-001', 'A5 dotted, 192 pages, lay-flat binding', 900, 15, 8),
  ('Seasonal Gift Box', 'GIFT-001', 'Curated selection of 4 Sunset Supply Co items', 4200, 10, 5);
